//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PagesRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PagesRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("School.Settings.Resources.PagesRes", typeof(PagesRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page System Accounting Main.
        /// </summary>
        public static string Accounting_Index {
            get {
                return ResourceManager.GetString("Accounting_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Activity System.
        /// </summary>
        public static string ActivitySystem {
            get {
                return ResourceManager.GetString("ActivitySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Show All Data For Trucks.
        /// </summary>
        public static string AllDataForTruck {
            get {
                return ResourceManager.GetString("AllDataForTruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllTrucksSuperviers.
        /// </summary>
        public static string AllTrucksSuperviers {
            get {
                return ResourceManager.GetString("AllTrucksSuperviers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Plan Trainings.
        /// </summary>
        public static string AnnualPlanTrainings {
            get {
                return ResourceManager.GetString("AnnualPlanTrainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Approved Chief Financial Officer.
        /// </summary>
        public static string Approved_ChiefFinancialOfficer {
            get {
                return ResourceManager.GetString("Approved_ChiefFinancialOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Page Approved Director Managers.
        /// </summary>
        public static string Approved_DirectorManag {
            get {
                return ResourceManager.GetString("Approved_DirectorManag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Approved General Managers.
        /// </summary>
        public static string Approved_GeneralManag {
            get {
                return ResourceManager.GetString("Approved_GeneralManag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Approved Secretary General.
        /// </summary>
        public static string Approved_SecretaryGeneral {
            get {
                return ResourceManager.GetString("Approved_SecretaryGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Areas.
        /// </summary>
        public static string AreasTrucks {
            get {
                return ResourceManager.GetString("AreasTrucks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Verify Password.
        /// </summary>
        public static string ASA {
            get {
                return ResourceManager.GetString("ASA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages Assign Pages To Role.
        /// </summary>
        public static string AssignPagesToRole {
            get {
                return ResourceManager.GetString("AssignPagesToRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Assign Pages To User.
        /// </summary>
        public static string AssignPagesToUser {
            get {
                return ResourceManager.GetString("AssignPagesToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Balance Audit.
        /// </summary>
        public static string BalanceAudit {
            get {
                return ResourceManager.GetString("BalanceAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Bills.
        /// </summary>
        public static string BuyBills {
            get {
                return ResourceManager.GetString("BuyBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Create Bill Buy .
        /// </summary>
        public static string BuyCreate {
            get {
                return ResourceManager.GetString("BuyCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Bills Exist Products .
        /// </summary>
        public static string BuyExist {
            get {
                return ResourceManager.GetString("BuyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chambers.
        /// </summary>
        public static string Chambers {
            get {
                return ResourceManager.GetString("Chambers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Accountings.
        /// </summary>
        public static string ChartAccountings {
            get {
                return ResourceManager.GetString("ChartAccountings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque.
        /// </summary>
        public static string Cheque {
            get {
                return ResourceManager.GetString("Cheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Complete Reverse Bill.
        /// </summary>
        public static string CompleteReverse {
            get {
                return ResourceManager.GetString("CompleteReverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigGroupsSuperviers.
        /// </summary>
        public static string ConfigGroupsSuperviers {
            get {
                return ResourceManager.GetString("ConfigGroupsSuperviers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts Employees.
        /// </summary>
        public static string Contracts {
            get {
                return ResourceManager.GetString("Contracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Create Orders Load Superviers.
        /// </summary>
        public static string CreateSupervier {
            get {
                return ResourceManager.GetString("CreateSupervier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custody.
        /// </summary>
        public static string Custody {
            get {
                return ResourceManager.GetString("Custody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Edit Custodies.
        /// </summary>
        public static string CustodyEdit {
            get {
                return ResourceManager.GetString("CustodyEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Custodies.
        /// </summary>
        public static string CustodyReport {
            get {
                return ResourceManager.GetString("CustodyReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments Adminstrative.
        /// </summary>
        public static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Derivers.
        /// </summary>
        public static string DeriverReport {
            get {
                return ResourceManager.GetString("DeriverReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derivers.
        /// </summary>
        public static string Derivers {
            get {
                return ResourceManager.GetString("Derivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Details Photos Trucks.
        /// </summary>
        public static string DetailsPotos {
            get {
                return ResourceManager.GetString("DetailsPotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divisions.
        /// </summary>
        public static string Divisions {
            get {
                return ResourceManager.GetString("Divisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditSupervier.
        /// </summary>
        public static string EditSupervier {
            get {
                return ResourceManager.GetString("EditSupervier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees Details.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Employees Salaries Report.
        /// </summary>
        public static string EmployeesSalariesReport {
            get {
                return ResourceManager.GetString("EmployeesSalariesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees Configurations Salaries.
        /// </summary>
        public static string EmpsConfigSalaries {
            get {
                return ResourceManager.GetString("EmpsConfigSalaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprise Branches.
        /// </summary>
        public static string EnterpriseBranches {
            get {
                return ResourceManager.GetString("EnterpriseBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Employees Centers.
        /// </summary>
        public static string EvaluationEmpCenters {
            get {
                return ResourceManager.GetString("EvaluationEmpCenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpenseDebenture.
        /// </summary>
        public static string ExpenseDebenture {
            get {
                return ResourceManager.GetString("ExpenseDebenture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Expense Debentures.
        /// </summary>
        public static string ExpenseDebenturesReport {
            get {
                return ResourceManager.GetString("ExpenseDebenturesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Dates Expires.
        /// </summary>
        public static string ExpiredDate {
            get {
                return ResourceManager.GetString("ExpiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Review Dates Expired.
        /// </summary>
        public static string ExpiredDeriversAndTrucks {
            get {
                return ResourceManager.GetString("ExpiredDeriversAndTrucks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father Accounts.
        /// </summary>
        public static string FatherAccounts {
            get {
                return ResourceManager.GetString("FatherAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms Members.
        /// </summary>
        public static string Forms {
            get {
                return ResourceManager.GetString("Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        public static string GetTaskTrucksReport {
            get {
                return ResourceManager.GetString("GetTaskTrucksReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Add User To Groups Messages.
        /// </summary>
        public static string GetUsersGroup {
            get {
                return ResourceManager.GetString("GetUsersGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Governorates.
        /// </summary>
        public static string Governorates {
            get {
                return ResourceManager.GetString("Governorates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prices Areas And Instance.
        /// </summary>
        public static string GPAreas {
            get {
                return ResourceManager.GetString("GPAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups Configurations Salaries Employees.
        /// </summary>
        public static string GroupConfigSalaryDetails {
            get {
                return ResourceManager.GetString("GroupConfigSalaryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Messages Users.
        /// </summary>
        public static string GroupMessages {
            get {
                return ResourceManager.GetString("GroupMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups Superviers.
        /// </summary>
        public static string GroupsSuperviers {
            get {
                return ResourceManager.GetString("GroupsSuperviers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main System.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page System HR Main.
        /// </summary>
        public static string HR_Index {
            get {
                return ResourceManager.GetString("HR_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Show Orders WorkShop Compelete.
        /// </summary>
        public static string IndexComplete {
            get {
                return ResourceManager.GetString("IndexComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Show Jobs Faults Compelete.
        /// </summary>
        public static string IndexCompleteWorkShop {
            get {
                return ResourceManager.GetString("IndexCompleteWorkShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Instructions.
        /// </summary>
        public static string InstructionsApplies {
            get {
                return ResourceManager.GetString("InstructionsApplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventories.
        /// </summary>
        public static string InventorXes {
            get {
                return ResourceManager.GetString("InventorXes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page System Inventory Main.
        /// </summary>
        public static string Inventory_Index {
            get {
                return ResourceManager.GetString("Inventory_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs Faults.
        /// </summary>
        public static string JobTasks {
            get {
                return ResourceManager.GetString("JobTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limition Accountings.
        /// </summary>
        public static string LimitionAccountings {
            get {
                return ResourceManager.GetString("LimitionAccountings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Limitions Accounts Report.
        /// </summary>
        public static string LimitionReports {
            get {
                return ResourceManager.GetString("LimitionReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Create Adances.
        /// </summary>
        public static string Loan {
            get {
                return ResourceManager.GetString("Loan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Edit Advances.
        /// </summary>
        public static string LoanFilterEdit {
            get {
                return ResourceManager.GetString("LoanFilterEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adances.
        /// </summary>
        public static string Loans {
            get {
                return ResourceManager.GetString("Loans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adances Employees.
        /// </summary>
        public static string LoansEmployees {
            get {
                return ResourceManager.GetString("LoansEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Manager.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MangerIndex.
        /// </summary>
        public static string MangerIndex {
            get {
                return ResourceManager.GetString("MangerIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MangerIndexSuperMenu.
        /// </summary>
        public static string MangerIndexSuperMenu {
            get {
                return ResourceManager.GetString("MangerIndexSuperMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members Details.
        /// </summary>
        public static string MemberDetails {
            get {
                return ResourceManager.GetString("MemberDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page System Membership Main.
        /// </summary>
        public static string Membership_Index {
            get {
                return ResourceManager.GetString("Membership_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationalities.
        /// </summary>
        public static string Nationalities {
            get {
                return ResourceManager.GetString("Nationalities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications System.
        /// </summary>
        public static string NotificationSystems {
            get {
                return ResourceManager.GetString("NotificationSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Show Derivers And Nationlity.
        /// </summary>
        public static string OneIndex {
            get {
                return ResourceManager.GetString("OneIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Orders WorkShop.
        /// </summary>
        public static string OrdersWorkShop {
            get {
                return ResourceManager.GetString("OrdersWorkShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Part Reverse Bill.
        /// </summary>
        public static string PartReverse {
            get {
                return ResourceManager.GetString("PartReverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personals.
        /// </summary>
        public static string Personals {
            get {
                return ResourceManager.GetString("Personals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotions.
        /// </summary>
        public static string Promotions {
            get {
                return ResourceManager.GetString("Promotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Debentures.
        /// </summary>
        public static string ReceiptDebentures {
            get {
                return ResourceManager.GetString("ReceiptDebentures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Receipt Debentures.
        /// </summary>
        public static string ReceiptDebenturesReport {
            get {
                return ResourceManager.GetString("ReceiptDebenturesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew.
        /// </summary>
        public static string Renew {
            get {
                return ResourceManager.GetString("Renew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Bills.
        /// </summary>
        public static string ReverseBills {
            get {
                return ResourceManager.GetString("ReverseBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Users.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Faults WorkShop.
        /// </summary>
        public static string RportFaultTasks {
            get {
                return ResourceManager.GetString("RportFaultTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Buy Bills.
        /// </summary>
        public static string RPTBuyBills {
            get {
                return ResourceManager.GetString("RPTBuyBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Bills.
        /// </summary>
        public static string SaleBills {
            get {
                return ResourceManager.GetString("SaleBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Sale Bills .
        /// </summary>
        public static string SaleBillsReport {
            get {
                return ResourceManager.GetString("SaleBillsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Create Sale Bill.
        /// </summary>
        public static string SaleCreate {
            get {
                return ResourceManager.GetString("SaleCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientific Disciplines.
        /// </summary>
        public static string ScientificDisciplines {
            get {
                return ResourceManager.GetString("ScientificDisciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sections Adminstrative.
        /// </summary>
        public static string Sections {
            get {
                return ResourceManager.GetString("Sections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Account.
        /// </summary>
        public static string SettingsAccounts {
            get {
                return ResourceManager.GetString("SettingsAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Search.
        /// </summary>
        public static string SmartSearch {
            get {
                return ResourceManager.GetString("SmartSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Show Groups Trucks In Superviers Menu.
        /// </summary>
        public static string SuperIndex {
            get {
                return ResourceManager.GetString("SuperIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Show Derivers For Superviers.
        /// </summary>
        public static string SupervierIndex {
            get {
                return ResourceManager.GetString("SupervierIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Show Derivers For Superviers.
        /// </summary>
        public static string SupervierIndexDerivers {
            get {
                return ResourceManager.GetString("SupervierIndexDerivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Show Orders Load Superviers.
        /// </summary>
        public static string SupervierIndexLoad {
            get {
                return ResourceManager.GetString("SupervierIndexLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupervierIndexLoadFilters.
        /// </summary>
        public static string SupervierIndexLoadFilters {
            get {
                return ResourceManager.GetString("SupervierIndexLoadFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupervierIndexTrucks.
        /// </summary>
        public static string SupervierIndexTrucks {
            get {
                return ResourceManager.GetString("SupervierIndexTrucks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupervierLoadsFilters.
        /// </summary>
        public static string SupervierLoadsFilters {
            get {
                return ResourceManager.GetString("SupervierLoadsFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Externals.
        /// </summary>
        public static string TaskExternals {
            get {
                return ResourceManager.GetString("TaskExternals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders Load.
        /// </summary>
        public static string TaskTrucks {
            get {
                return ResourceManager.GetString("TaskTrucks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Requests Shipping.
        /// </summary>
        public static string TaskTrucksReport {
            get {
                return ResourceManager.GetString("TaskTrucksReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technicians.
        /// </summary>
        public static string Technicians {
            get {
                return ResourceManager.GetString("Technicians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Technicians.
        /// </summary>
        public static string TechTasksReports {
            get {
                return ResourceManager.GetString("TechTasksReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Centers.
        /// </summary>
        public static string TrainingCenters {
            get {
                return ResourceManager.GetString("TrainingCenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Tranaction Stores.
        /// </summary>
        public static string TranactionReport {
            get {
                return ResourceManager.GetString("TranactionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page System Transport Main.
        /// </summary>
        public static string Transport_Index {
            get {
                return ResourceManager.GetString("Transport_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trianing Courses.
        /// </summary>
        public static string TrianingCourses {
            get {
                return ResourceManager.GetString("TrianingCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Trucks.
        /// </summary>
        public static string TruckReport {
            get {
                return ResourceManager.GetString("TruckReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trucks.
        /// </summary>
        public static string Trucks {
            get {
                return ResourceManager.GetString("Trucks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universities.
        /// </summary>
        public static string Universities {
            get {
                return ResourceManager.GetString("Universities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Assign User .
        /// </summary>
        public static string UserToGroup {
            get {
                return ResourceManager.GetString("UserToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Add User To Role Promission.
        /// </summary>
        public static string UserToRole {
            get {
                return ResourceManager.GetString("UserToRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Vacation.
        /// </summary>
        public static string VacationApplies {
            get {
                return ResourceManager.GetString("VacationApplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacations.
        /// </summary>
        public static string Vacations {
            get {
                return ResourceManager.GetString("Vacations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page System WorkShop Main.
        /// </summary>
        public static string WorkShop_Index {
            get {
                return ResourceManager.GetString("WorkShop_Index", resourceCulture);
            }
        }
    }
}
